'use strict';
const fullName = 'CharLee-Kyle Gaff';
console.log('value of fullName: ' + fullName);
const isCool = true;
console.log('Kyle is cool: ' + isCool);
const numberOfPets = 2;
console.log('I have ' + numberOfPets + ' pets');
console.log('typeof fullName: ' + typeof fullName);
console.log('type of isCool: ' + typeof isCool);
console.log('type of numberOfPets: ' + typeof numberOfPets);
const empty = null;
console.log('value of empty: ' + empty);
console.log('typeof empty: ' + typeof empty);
let nothing;
console.log('value of nothing: ' + nothing);
console.log('typeof nothing: ' + typeof nothing);
