'use strict';
const width = 7;
const height = 12;
const area = width * height;
console.log('value of the area: ' + area);
console.log('typeof area: ' + typeof area);
const bill = 300;
const payment = 150;
const change = bill - payment;
console.log('remaining balance: ' + change);
console.log('typeof change' + typeof change);
const quizzes = 80;
const midterm = 89;
const final = 98;
const average = (final + midterm + quizzes) / 3;
console.log('Final grade: ' + average);
console.log('typeof average: ' + typeof average);
const firstName = 'CharLee-Kyle';
const lastName = 'Gaff';
const fullName = firstName + lastName;
console.log('My name is: ' + fullName);
console.log('type of fullName: ' + typeof fullName);
const pH = 10;
const isAcidic = pH < 7;
console.log('value of isAcidic: ' + isAcidic);
console.log('type of isAcidic: ' + typeof isAcidic);
const headCount = 300;
const isSparta = headCount === 300;
console.log('value of isSparta: ' + isSparta);
console.log('typeof isSparta: ' + typeof isSparta);
const motto = fullName + ' is the GOAT';
console.log(motto);
console.log('typeof motto: ' + typeof motto);
